name: GitHub Pages

on:
  push:
    branches:
      - main  # Ana branch "main" değilse "master" yazabilirsin.

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MkDocs
        run: |
          pip install mkdocs  # MkDocs'u kuruyoruz

      - name: Build the site
        run: |
          mkdocs build  # MkDocs build komutuyla siteyi oluşturuyoruz

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # MkDocs'un oluşturduğu "site" klasörünü deploy ediyoruz
