name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Eğer branch'in farklıysa, burayı değiştir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install mkdocs-material pymdown-extensions mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
